name: Docker Hub Description

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/dockerhub_description.yaml

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: giovanigm/flutter
          readme-filepath: ./README.md
          short-description: ${{ github.event.repository.description }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: giovanigm/flutter-cache
          readme-filepath: ./README.md
          short-description: ${{ github.event.repository.description }}
